interface User {
    name: string
    clientIds: string[]
}

interface Client {
    id: string
}

interface Kill {
    from: Client
    to: Client
    cause: MeanOfDeath
}

interface Join {
    startTime: number
    endTime?: number
    client: Client
    team: number
    name: string
}

interface Game {
    kills: Kill[]
    joins: Join[]
    awards: Award[]
}